# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstr', '0002_remove_bookbuytrans_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookbuytrans',
            unique_together=set([]),
        ),
    ]
