# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstr', '0003_auto_20171202_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='cust_id',
            new_name='own_id',
        ),
    ]
